### ISSUE TITLE
Add pywgrib2_s testing via pywgrib2_s_cookbook.tgz

### ISSUE THREAD

**Issue by EWBr0wn** [EWBr0wn/packaging-wgrib2#5]
Testing suite found at https://ftp.cpc.ncep.noaa.gov/wd51we/pywgrib2_s/pywgrib2_s_cookbook.tgz

Applies to the following:
* v0.0.11
* v1.0.0

**Comment by EWBr0wn** [comment]
# cookbook_read_write.py test not working

```
/tmp/cookbook_s# ./clean.sh ; q="" ; ess=0 ; \
for py in $(ls -1 cookbook_*.py | grep cookbook_read_write.py) ; do 
  printf "%s:\n" "${py}"
  ./${py}
  ess=$(expr $? + ${ess})
  if [ ${ess} -ne 0 ] ; then
    echo ${py} ${ess}
    ess=0
    read q
  fi
done ; echo ${ess}
```

```
cookbook_read_write.py:
finished loading libraries
pywgrib2_s v0.0.10 11-9-2020 w. ebisuzaki
data shape= (192, 94)
data isfortran= True
bottom left lat/lon,val= -88.54195 0.0 50000.0
data2 shape= (192, 94)
data2 isfortran= False
write field= 1:0:D=20200131180000:WEASD:surface:6 hour fcst:
Traceback (most recent call last):
  File "/tmp/cookbook_s/./cookbook_read_write.py", line 56, in <module>
    vector=numpy.zeros((numpy.size(data)),dtype=numpy.int)
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 313, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?
cookbook_read_write.py 1
```

**Comment by EWBr0wn** [comment]
# Patch cookbook_read_write.py

pywgrib2_s version does not matter.  The root issue is numpy.

```
# diff cookbook_read_write.py t-cookbook_read_write.py
56c56
< vector=numpy.zeros((numpy.size(data)),dtype=numpy.int)
---
> vector=numpy.zeros((numpy.size(data)),dtype=int)
```

```
/tmp/cookbook_s# ./t-cookbook_read_write.py
finished loading libraries
pywgrib2_s v1.0.0 11-21-2022 w. ebisuzaki
data shape= (192, 94)
data isfortran= True
bottom left lat/lon,val= -88.54195 0.0 50000.0
data2 shape= (192, 94)
data2 isfortran= False
write field= 1:0:D=20200131180000:WEASD:surface:6 hour fcst:
write field= 1:0:D=20200131180000:WEASD:surface:6 hour fcst:
done copy= a_copy.grb  write= a_write.grb  write_c= a_write_c.grb  write_l= a_write_l.grb
/tmp/cookbook_s# echo $?
0
```
